name: Build and test

on:
  workflow_call:
    inputs:
      test_flags:
        description: 'Extra flags to be used with the go test step'
        required: false
        type: string

jobs:

  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repoistory
      uses: actions/checkout@main
      with:
        fetch-depth: 2  # Needed I think for the test coverage report.
    
    - name: Get latest go version
      run: echo "latest_go_version=$(curl https://go.dev/VERSION?m=text | cut -c 3-)" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: ${{ env.latest_go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test and run coverage
      run: go test -v ./... -coverprofile=coverage.out -covermode=atomic ${{ inputs.test_flags }}

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
