name: Build and test

on:
  workflow_call:
    inputs:
      test_flags:
        description: 'Extra flags to be used with the go test step'
        required: false
        type: string

jobs:

  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repoistory
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Needed I think for the test coverage report.
    
    - name: Get latest go version
      run: echo "latest_go_version=$(curl https://go.dev/VERSION?m=text | grep -oP '(\d+\.\d+\.\d+)')" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.latest_go_version }}

    - name: Build
      run: find . -name '*.go' -execdir go build -v \;
      # This command will search for all Go files in the current directory and all subdirectories. For each Go file found, it will change to the directory of the file (execdir) and execute go build -v.
      # Please note that go build will only build packages, not individual files. If a directory does not contain a package, go build will not do anything

    - name: Test and run coverage
      run: find . -name '*.go' -execdir go test -v -coverprofile=coverage.out -covermode=atomic ${{ inputs.test_flags }} \;

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
