name: Deploy cloud function

on:
  workflow_call:
    inputs:
      function_name:
        description: 'Name of cloud function'
        required: true
        type: string
    secrets:
      WIP:
        required: true
      SA:
        required: true
      GAP:
        required: true
# Can't store these secret locally in the repoistory, they must be passed from the calling workflow.

jobs:
  deploy:
    name: Deploy cloud function
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIP }}
          service_account: ${{ secrets.SA }}
          project_id: pickmypostcode3
# This was setup using: https://github.com/google-github-actions/auth#setup
# This might also be useful: https://www.youtube.com/watch?v=ZgVhU5qvK1M

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Deploy
        run: 'gcloud functions deploy  ${{ inputs.function_name }} --gen2 --runtime=go121 --region=us-west1 --trigger-http --allow-unauthenticated --entry-point=HelloHTTP --memory=2Gi --timeout=300s --set-env-vars=GOOGLEAPPPASSWORD=${{ secrets.GAP }} --max-instances=1'
