name: Go Linter

on:
  workflow_call:

jobs:
  build:
    name: Lint Go Code
    runs-on: ubuntu-latest

    steps:
      # Get the code.
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Run the static check of the code, which is a sort of official "state of the art linter". Also installs go.
      - name: Static check
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"

      # Run the go vet command which is a sort of go code checker.
      - name: Vet
        run: go vet -v ./...
