name: Refresh go report card

on:
  workflow_call:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  post-request:
    name: Update go report card
    runs-on: ubuntu-latest
    steps:
      - name: Execute Request
        run: curl -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks
