name: Release Please

on:
  workflow_call:

jobs:
  release-please:
    name: Call release please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: go
