name: Release Please

on:
  workflow_call:
    secrets:
      RELEASE_PLEASE_TOKEN:
        required: true

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  release-please:
    name: Call release please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }} # Needs to use a PAT token to trigger GitHub Actions CI Checks.
          release-type: go
