name: Release Please

on:
  workflow_call:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  release-please:
    name: Call release please
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }} # Needs to use a PAT token to trigger Github Actions CI Checks.
          release-type: go
