name: Auto tag and release

on:
  push:
    branches: [master]

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  tag-and-release:
    name: Tag and release
    runs-on: ubuntu-latest

    # Explicitly grant permissions to the GITHUB_TOKEN. Required to push tags and create releases.
    permissions:
      contents: write

    steps:
      # Get the code.
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0 # Required to fetch all tags for semantic versioning

      - name: Create a GitHub release
        run: gh release create --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

